# Generated by Django 4.2.6 on 2024-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="administrator_flag",
            new_name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deletion_flag",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
