# Generated by Django 4.2.6 on 2024-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_administrator_flag_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="administrator_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_flag",
            field=models.BooleanField(default=False),
        ),
    ]
