# Generated by Django 4.2.6 on 2024-11-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_administrator_flag_user_deletion_flag"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
