# Generated by Django 4.2.5 on 2025-01-22 01:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=accounts.models.generate_unique_id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
