# Generated by Django 4.2.6 on 2024-11-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerInformation",
            fields=[
                ("career_id", models.AutoField(primary_key=True, serialize=False)),
                ("career", models.CharField(max_length=255)),
                ("speciality_height", models.IntegerField()),
            ],
            options={
                "db_table": "career_information",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField()),
                ("update_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Category",
            },
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "qualification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("qualification_name", models.CharField(max_length=255)),
                ("speciality_height", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "credentials",
            },
        ),
        migrations.CreateModel(
            name="JobTitleInformation",
            fields=[
                ("job_title_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=255)),
                ("speciality_height", models.IntegerField()),
                ("planning_presentation_power", models.IntegerField()),
                ("teamwork", models.IntegerField()),
                ("time_management_ability", models.IntegerField()),
                ("problem_solving_ability", models.IntegerField()),
            ],
            options={
                "db_table": "job_title_information",
            },
        ),
        migrations.CreateModel(
            name="MBTI",
            fields=[
                ("mbti_id", models.AutoField(primary_key=True, serialize=False)),
                ("mbti_name", models.CharField(max_length=255)),
                ("planning_presentation_power", models.CharField(max_length=255)),
                ("teamwork", models.CharField(max_length=255)),
                ("time_management_ability", models.CharField(max_length=255)),
                ("problem_solving_ability", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "MBTI",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("birthdate", models.DateTimeField()),
                ("job_title", models.CharField(max_length=255)),
                ("memo", models.TextField()),
                ("creation_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                (
                    "mbti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.mbti"
                    ),
                ),
            ],
            options={
                "db_table": "Member",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=255)),
                ("project_detail", models.TextField(blank=True, null=True)),
                ("project_start_date", models.DateTimeField()),
                ("project_end_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("update_date", models.DateTimeField(blank=True, null=True)),
                ("complete_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("post_evaluation_memo", models.TextField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                ("complete_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Project",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255)),
                ("count", models.IntegerField(blank=True, null=True)),
                ("objective", models.TextField(blank=True, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField()),
                ("update_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Team",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("team_member_id", models.AutoField(primary_key=True, serialize=False)),
                ("deletion_flag", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.team"
                    ),
                ),
            ],
            options={
                "db_table": "Team_Member",
            },
        ),
        migrations.CreateModel(
            name="ProjectProgressStatus",
            fields=[
                (
                    "progress_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("phase_name", models.CharField(max_length=255)),
                ("complete_flag", models.BooleanField()),
                ("deletion_flag", models.BooleanField()),
                ("expiration_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("complete_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_progress_status",
            },
        ),
        migrations.CreateModel(
            name="ProjectAffiliationTeam",
            fields=[
                (
                    "project_affiliation_team_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("deletion_flag", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField()),
                ("change_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.team"
                    ),
                ),
            ],
            options={
                "db_table": "Project_Affiliation_Team",
            },
        ),
        migrations.CreateModel(
            name="MemberParameter",
            fields=[
                ("parameter_id", models.AutoField(primary_key=True, serialize=False)),
                ("planning_presentation_power", models.IntegerField()),
                ("teamwork", models.IntegerField()),
                ("time_management_ability", models.IntegerField()),
                ("problem_solving_ability", models.IntegerField()),
                ("speciality_height", models.IntegerField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_parameter",
            },
        ),
        migrations.CreateModel(
            name="MemberList",
            fields=[
                ("member_list_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=255)),
                ("memo", models.TextField()),
                ("creation_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.category",
                    ),
                ),
                (
                    "mbti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.mbti"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
            ],
            options={
                "db_table": "Member_List",
            },
        ),
        migrations.CreateModel(
            name="MemberHoldingQualification",
            fields=[
                (
                    "holding_qualification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("creation_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.credentials",
                    ),
                ),
            ],
            options={
                "db_table": "member_holding_qualification",
            },
        ),
        migrations.CreateModel(
            name="MemberCareer",
            fields=[
                (
                    "member_career_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("creation_date", models.DateTimeField()),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.careerinformation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_career",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("priority_flag", models.BooleanField()),
                ("deletion_flag", models.BooleanField()),
                ("expiration_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "member1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_member1",
                        to="canri_app.member",
                    ),
                ),
                (
                    "member2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_member2",
                        to="canri_app.member",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.project",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
            },
        ),
    ]
