# Generated by Django 4.2.6 on 2024-11-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                ("administrator_flag", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
