# Generated by Django 4.2.6 on 2024-11-08 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="MBTI",
            fields=[
                ("mbti_id", models.AutoField(primary_key=True, serialize=False)),
                ("mbti_name", models.CharField(max_length=255)),
                ("planning_presentation_power", models.TextField()),
                ("teamwork", models.TextField()),
                ("time_management_ability", models.TextField()),
                ("problem_solving_ability", models.TextField()),
            ],
            options={
                "db_table": "mbti",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("birthdate", models.DateTimeField()),
                ("job_title", models.CharField(max_length=255)),
                ("memo", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                (
                    "mbti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.mbti"
                    ),
                ),
            ],
            options={
                "db_table": "member",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=255)),
                ("project_detail", models.TextField(blank=True, null=True)),
                ("project_start_date", models.DateTimeField()),
                ("project_end_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("complete_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("post_evaluation_memo", models.TextField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                ("complete_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255)),
                ("count", models.IntegerField(blank=True, null=True)),
                ("objective", models.TextField(blank=True, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                ("administrator_flag", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("team_member_id", models.AutoField(primary_key=True, serialize=False)),
                ("deletion_flag", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.user"
                    ),
                ),
            ],
            options={
                "db_table": "team_member",
            },
        ),
        migrations.CreateModel(
            name="ProjectAffiliationTeam",
            fields=[
                (
                    "project_affiliation_team_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("deletion_flag", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("change_date", models.DateTimeField(auto_now=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.team"
                    ),
                ),
            ],
            options={
                "db_table": "project_affiliation_team",
            },
        ),
        migrations.CreateModel(
            name="MemberList",
            fields=[
                ("member_list_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=255)),
                ("memo", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.category",
                    ),
                ),
                (
                    "mbti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.mbti"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_list",
            },
        ),
    ]
