# Generated by Django 4.2.6 on 2024-11-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerInformation",
            fields=[
                ("career_id", models.AutoField(primary_key=True, serialize=False)),
                ("career", models.CharField(max_length=255)),
                ("speciality_height", models.IntegerField()),
                ("creation_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canri_app.user"
                    ),
                ),
            ],
            options={
                "db_table": "career_information",
            },
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "qualification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("qualification_name", models.CharField(max_length=255)),
                ("speciality_height", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "credentials",
            },
        ),
        migrations.CreateModel(
            name="JobTitleInformation",
            fields=[
                ("job_title_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=255)),
                ("speciality_height", models.IntegerField()),
                ("planning_presentation_power", models.IntegerField()),
                ("teamwork", models.IntegerField()),
                ("time_management_ability", models.IntegerField()),
                ("problem_solving_ability", models.IntegerField()),
            ],
            options={
                "db_table": "job_title_information",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="planning_presentation_power",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="problem_solving_ability",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="teamwork",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="time_management_ability",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="member",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="memberlist",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectaffiliationteam",
            name="change_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectaffiliationteam",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="creation_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="update_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name="category",
            table="Category",
        ),
        migrations.AlterModelTable(
            name="mbti",
            table="MBTI",
        ),
        migrations.AlterModelTable(
            name="member",
            table="Member",
        ),
        migrations.AlterModelTable(
            name="memberlist",
            table="Member_List",
        ),
        migrations.AlterModelTable(
            name="project",
            table="Project",
        ),
        migrations.AlterModelTable(
            name="projectaffiliationteam",
            table="Project_Affiliation_Team",
        ),
        migrations.AlterModelTable(
            name="team",
            table="Team",
        ),
        migrations.AlterModelTable(
            name="teammember",
            table="Team_Member",
        ),
        migrations.CreateModel(
            name="ProjectProgressStatus",
            fields=[
                (
                    "progress_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("phase_name", models.CharField(max_length=255)),
                ("complete_flag", models.BooleanField()),
                ("deletion_flag", models.BooleanField()),
                ("expiration_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("complete_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_progress_status",
            },
        ),
        migrations.CreateModel(
            name="MemberParameter",
            fields=[
                ("parameter_id", models.AutoField(primary_key=True, serialize=False)),
                ("planning_presentation_power", models.IntegerField()),
                ("teamwork", models.IntegerField()),
                ("time_management_ability", models.IntegerField()),
                ("problem_solving_ability", models.IntegerField()),
                ("speciality_height", models.IntegerField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_parameter",
            },
        ),
        migrations.CreateModel(
            name="MemberHoldingQualification",
            fields=[
                (
                    "holding_qualification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("creation_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_flag", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.credentials",
                    ),
                ),
            ],
            options={
                "db_table": "member_holding_qualification",
            },
        ),
        migrations.CreateModel(
            name="MemberCareer",
            fields=[
                (
                    "member_career_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("creation_date", models.DateTimeField()),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.careerinformation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_career",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("priority_flag", models.BooleanField()),
                ("deletion_flag", models.BooleanField()),
                ("expiration_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("deletion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "member1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_member1",
                        to="canri_app.member",
                    ),
                ),
                (
                    "member2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_member2",
                        to="canri_app.member",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canri_app.project",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
            },
        ),
    ]
