# Generated by Django 4.2.6 on 2024-11-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0002_remove_memberlist_member_memberlist_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberlist",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="memberlist",
            name="mbti",
        ),
        migrations.RemoveField(
            model_name="memberlist",
            name="memo",
        ),
        migrations.RemoveField(
            model_name="memberlist",
            name="member",
        ),
        migrations.AddField(
            model_name="memberlist",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="canri_app.member",
            ),
            preserve_default=False,
        ),
    ]
