# Generated by Django 4.2.6 on 2024-11-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "canri_app",
            "0003_remove_memberlist_job_title_remove_memberlist_mbti_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="member_id",
            new_name="member",
        ),
    ]
