# Generated by Django 4.2.6 on 2024-11-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0004_rename_member_id_teammember_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mbti",
            name="planning_presentation_power",
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="problem_solving_ability",
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="teamwork",
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mbti",
            name="time_management_ability",
            field=models.IntegerField(max_length=255),
        ),
    ]
