# Generated by Django 4.2.6 on 2024-11-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0005_alter_mbti_planning_presentation_power_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_start_date",
            field=models.DateField(),
        ),
    ]
