# Generated by Django 4.2.5 on 2024-11-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canri_app', '0006_alter_project_complete_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='planning_presentation_power',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='problem_solving_ability',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='teamwork',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='time_management_ability',
        ),
    ]
