# Generated by Django 4.2.6 on 2024-11-22 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0007_remove_mbti_planning_presentation_power_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="job_title",
        ),
        migrations.AddField(
            model_name="member",
            name="job_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="canri_app.jobtitleinformation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectprogressstatus",
            name="complete_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="projectprogressstatus",
            name="deletion_flag",
            field=models.BooleanField(default=False),
        ),
    ]
