# Generated by Django 4.2.6 on 2024-11-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0009_rename_job_id_member_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="mbti",
            name="planning_presentation_power",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mbti",
            name="problem_solving_ability",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mbti",
            name="teamwork",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mbti",
            name="time_management_ability",
            field=models.IntegerField(default=0),
        ),
    ]
