<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-11-27 03:07
=======
# Generated by Django 4.2.6 on 2024-11-27 02:50
>>>>>>> d302c472e13700eaa5b4ca7d0ed2dedad8e9bb14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0010_mbti_planning_presentation_power_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="expiration_date",
        ),
    ]
