# Generated by Django 4.2.6 on 2024-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0011_remove_feedback_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectprogressstatus",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
