# Generated by Django 4.2.6 on 2024-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0011_remove_feedback_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
