# Generated by Django 4.2.6 on 2024-11-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0012_feedback_expiration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="expiration_date",
        ),
    ]
