# Generated by Django 4.2.6 on 2024-11-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canri_app", "0013_remove_feedback_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberparameter",
            name="speciality_height",
            field=models.FloatField(),
        ),
    ]
