# Generated by Django 4.2.5 on 2025-01-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canri_app', '0012_alter_projectprogressstatus_expiration_date'),
        ('canri_app', '0014_alter_memberparameter_speciality_height'),
    ]

    operations = [
    ]
